/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b6e8625a8799601024fff6658d2a8442)
interface __BaseEnv_Env {
	PRODUCTION: D1Database;
	SANDBOX: D1Database;
	SLACK_CONFIG_TOKEN: SecretsStoreSecret;
	SLACK_CONFIG_REFRESH_TOKEN: SecretsStoreSecret;
	CLOUDFLARE_ACCOUNT_ID: "281f6b8969eb59a0dec34daaafd69a29";
	SECRETS_STORE_ID: "5376e6440f0a470496364c1a036ecac8";
	SLACK_APP_ID: "A0A3U1V7LM4";
	CLOUDFLARE_TOKEN: string;
	OBOIST_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID" | "SECRETS_STORE_ID" | "SLACK_APP_ID" | "CLOUDFLARE_TOKEN" | "OBOIST_SECRET">> {}
}
